#!/usr/bin/env bash
# Should get updates
# it installs nginx and configure it to listen on port 80
# should print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
