#!/usr/bin/env bash
# it fixs nginx listening on port 80
# It should go to sites-enabled folder for Nginx
cd /etc/nginx/sites-enabled/ || exit;
# It must remove the default file
rm default;
# It creates symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restarti
